//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"

namespace PermitSDK.AspNet.Services
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record AllTenantsAuthorizationResult
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public AllTenantsAuthorizationResult(System.Collections.Generic.ICollection<_AllTenantsAuthorizationResult> @allowed_tenants)

        {

            this.Allowed_tenants = @allowed_tenants;

        }
        [System.Text.Json.Serialization.JsonPropertyName("allowed_tenants")]
        public System.Collections.Generic.ICollection<_AllTenantsAuthorizationResult> Allowed_tenants { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// the format of is_allowed() input
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record AuthorizationQuery
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public AuthorizationQuery(string @action, object @context, Resource @resource, string @sdk, User @user)

        {

            this.User = @user;

            this.Action = @action;

            this.Resource = @resource;

            this.Context = @context;

            this.Sdk = @sdk;

        }
        [System.Text.Json.Serialization.JsonPropertyName("user")]
        [System.ComponentModel.DataAnnotations.Required]
        public User User { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("action")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Action { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("resource")]
        [System.ComponentModel.DataAnnotations.Required]
        public Resource Resource { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("context")]
        public object Context { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("sdk")]
        public string Sdk { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// the format of is_allowed() input
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record AuthorizationQueryV1
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public AuthorizationQueryV1(string @action, object @context, ResourceV1 @resource, string @user)

        {

            this.User = @user;

            this.Action = @action;

            this.Resource = @resource;

            this.Context = @context;

        }
        [System.Text.Json.Serialization.JsonPropertyName("user")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string User { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("action")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Action { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("resource")]
        [System.ComponentModel.DataAnnotations.Required]
        public ResourceV1 Resource { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("context")]
        public object Context { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record AuthorizationResult
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public AuthorizationResult(bool? @allow, object @debug, object @query, bool? @result)

        {

            this.Allow = @allow;

            this.Query = @query;

            this.Debug = @debug;

            this.Result = @result;

        }
        [System.Text.Json.Serialization.JsonPropertyName("allow")]
        public bool? Allow { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("query")]
        public object Query { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("debug")]
        public object Debug { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public bool? Result { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record BulkAuthorizationResult
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public BulkAuthorizationResult(System.Collections.Generic.ICollection<AuthorizationResult> @allow)

        {

            this.Allow = @allow;

        }
        [System.Text.Json.Serialization.JsonPropertyName("allow")]
        public System.Collections.Generic.ICollection<AuthorizationResult> Allow { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// an entry in the callbacks register.
    /// <br/>
    /// <br/>this schema is used by the callbacks api
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record CallbackEntry
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public CallbackEntry(HttpFetcherConfig @config, string @key, string @url)

        {

            this.Key = @key;

            this.Url = @url;

            this.Config = @config;

        }    /// <summary>
        /// unique id to identify this callback (optional)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("key")]
        public string Key { get; init; }

        /// <summary>
        /// http/https url to call back on update
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Url { get; init; }

        /// <summary>
        /// optional http config for the target url (i.e: http method, headers, etc)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("config")]
        public HttpFetcherConfig Config { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record HTTPValidationError
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public HTTPValidationError(System.Collections.Generic.ICollection<ValidationError> @detail)

        {

            this.Detail = @detail;

        }
        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        public System.Collections.Generic.ICollection<ValidationError> Detail { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Config for HttpFetchProvider's Adding HTTP headers.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record HttpFetcherConfig
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public HttpFetcherConfig(object @data, string @fetcher, object @headers, bool? @is_json, HttpMethods? @method, bool? @process_data)

        {

            this.Fetcher = @fetcher;

            this.Headers = @headers;

            this.Is_json = @is_json;

            this.Process_data = @process_data;

            this.Method = @method;

            this.Data = @data;

        }    /// <summary>
        /// indicates to OPAL client that it should use a custom FetcherProvider to fetch the data
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fetcher")]
        public string Fetcher { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("headers")]
        public object Headers { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("is_json")]
        public bool? Is_json { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("process_data")]
        public bool? Process_data { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("method")]
        public HttpMethods? Method { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public object Data { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// An enumeration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum HttpMethods
    {

        [System.Runtime.Serialization.EnumMember(Value = @"get")]
        Get = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"post")]
        Post = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"put")]
        Put = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"patch")]
        Patch = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"head")]
        Head = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"delete")]
        Delete = 5,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationInput
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationInput(string @client_ip, KongAuthorizationInputConsumer @consumer, KongAuthorizationInputRequest @request, KongAuthorizationInputRoute @route, KongAuthorizationInputService @service)

        {

            this.Request = @request;

            this.Client_ip = @client_ip;

            this.Service = @service;

            this.Route = @route;

            this.Consumer = @consumer;

        }
        [System.Text.Json.Serialization.JsonPropertyName("request")]
        [System.ComponentModel.DataAnnotations.Required]
        public KongAuthorizationInputRequest Request { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("client_ip")]
        public string Client_ip { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("service")]
        public KongAuthorizationInputService Service { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("route")]
        public KongAuthorizationInputRoute Route { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("consumer")]
        public KongAuthorizationInputConsumer Consumer { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationInputConsumer
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationInputConsumer(System.Guid @id, string @username)

        {

            this.Id = @id;

            this.Username = @username;

        }
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationInputRequest
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationInputRequest(KongAuthorizationInputRequestHttp @http)

        {

            this.Http = @http;

        }
        [System.Text.Json.Serialization.JsonPropertyName("http")]
        [System.ComponentModel.DataAnnotations.Required]
        public KongAuthorizationInputRequestHttp Http { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationInputRequestHttp
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationInputRequestHttp(System.Collections.Generic.IDictionary<string, string> @headers, string @host, string @method, string @path, int @port, System.Collections.Generic.IDictionary<string, string> @querystring, string @scheme, object @tls)

        {

            this.Host = @host;

            this.Port = @port;

            this.Tls = @tls;

            this.Method = @method;

            this.Scheme = @scheme;

            this.Path = @path;

            this.Querystring = @querystring;

            this.Headers = @headers;

        }
        [System.Text.Json.Serialization.JsonPropertyName("host")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Host { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("port")]
        public int Port { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("tls")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Tls { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("method")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Method { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("scheme")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Scheme { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("path")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Path { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("querystring")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.IDictionary<string, string> Querystring { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("headers")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.IDictionary<string, string> Headers { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationInputRoute
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationInputRoute(int @created_at, int @https_redirect_status_code, System.Guid @id, string @path_handling, System.Collections.Generic.ICollection<string> @paths, bool @preserve_host, System.Collections.Generic.ICollection<string> @protocols, int @regex_priority, bool @request_buffering, bool @response_buffering, KongAuthorizationInputRouteService @service, bool @strip_path, int @updated_at, System.Guid @ws_id)

        {

            this.Id = @id;

            this.Paths = @paths;

            this.Protocols = @protocols;

            this.Strip_path = @strip_path;

            this.Created_at = @created_at;

            this.Ws_id = @ws_id;

            this.Request_buffering = @request_buffering;

            this.Updated_at = @updated_at;

            this.Preserve_host = @preserve_host;

            this.Regex_priority = @regex_priority;

            this.Response_buffering = @response_buffering;

            this.Https_redirect_status_code = @https_redirect_status_code;

            this.Path_handling = @path_handling;

            this.Service = @service;

        }
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("paths")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<string> Paths { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("protocols")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<string> Protocols { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("strip_path")]
        public bool Strip_path { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public int Created_at { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("ws_id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Ws_id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("request_buffering")]
        public bool Request_buffering { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public int Updated_at { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("preserve_host")]
        public bool Preserve_host { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("regex_priority")]
        public int Regex_priority { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("response_buffering")]
        public bool Response_buffering { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("https_redirect_status_code")]
        public int Https_redirect_status_code { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("path_handling")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Path_handling { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("service")]
        [System.ComponentModel.DataAnnotations.Required]
        public KongAuthorizationInputRouteService Service { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationInputRouteService
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationInputRouteService(System.Guid @id)

        {

            this.Id = @id;

        }
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationInputService
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationInputService(int @connect_timeout, int @created_at, string @host, System.Guid @id, string @name, int @port, string @procotol, int @read_timeout, int @retries, int @updated_at, int @write_timeout, System.Guid @ws_id)

        {

            this.Host = @host;

            this.Created_at = @created_at;

            this.Connect_timeout = @connect_timeout;

            this.Id = @id;

            this.Procotol = @procotol;

            this.Name = @name;

            this.Read_timeout = @read_timeout;

            this.Port = @port;

            this.Updated_at = @updated_at;

            this.Ws_id = @ws_id;

            this.Retries = @retries;

            this.Write_timeout = @write_timeout;

        }
        [System.Text.Json.Serialization.JsonPropertyName("host")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Host { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public int Created_at { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("connect_timeout")]
        public int Connect_timeout { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("procotol")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Procotol { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("read_timeout")]
        public int Read_timeout { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("port")]
        public int Port { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public int Updated_at { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("ws_id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Ws_id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("retries")]
        public int Retries { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("write_timeout")]
        public int Write_timeout { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// the format of is_allowed_kong() input
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationQuery
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationQuery(KongAuthorizationInput @input)

        {

            this.Input = @input;

        }
        [System.Text.Json.Serialization.JsonPropertyName("input")]
        [System.ComponentModel.DataAnnotations.Required]
        public KongAuthorizationInput Input { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record KongAuthorizationResult
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public KongAuthorizationResult(bool? @result)

        {

            this.Result = @result;

        }
        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public bool? Result { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record Message
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public Message(string @detail)

        {

            this.Detail = @detail;

        }
        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Detail { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// represents a policy store endpoint - contains the policy store's:
    /// <br/>- location (url)
    /// <br/>- type
    /// <br/>- credentials
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record PolicyStoreDetails
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public PolicyStoreDetails(string @token, PolicyStoreTypes? @type, string @url)

        {

            this.Type = @type;

            this.Url = @url;

            this.Token = @token;

        }    /// <summary>
        /// the type of policy store, currently only OPA is officially supported
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public PolicyStoreTypes? Type { get; init; }

        /// <summary>
        /// the url that OPA can be found in. if localhost is the host - it means OPA is on the same hostname as OPAL client.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Url { get; init; }

        /// <summary>
        /// optional access token required by the policy store
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("token")]
        public string Token { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// An enumeration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PolicyStoreTypes
    {

        [System.Runtime.Serialization.EnumMember(Value = @"OPA")]
        OPA = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"MOCK")]
        MOCK = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record Resource
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public Resource(object @attributes, object @context, string @key, string @tenant, string @type)

        {

            this.Type = @type;

            this.Key = @key;

            this.Tenant = @tenant;

            this.Attributes = @attributes;

            this.Context = @context;

        }
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("key")]
        public string Key { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("tenant")]
        public string Tenant { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("attributes")]
        public object Attributes { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("context")]
        public object Context { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.Obsolete]
    public partial record ResourceV1
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ResourceV1(object @attributes, object @context, string @id, string @tenant, string @type)

        {

            this.Type = @type;

            this.Id = @id;

            this.Tenant = @tenant;

            this.Attributes = @attributes;

            this.Context = @context;

        }
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("tenant")]
        public string Tenant { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("attributes")]
        public object Attributes { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("context")]
        public object Context { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record SyncedRole
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public SyncedRole(string @id, object @metadata, string @name, System.Collections.Generic.ICollection<string> @permissions, string @tenant_id)

        {

            this.Id = @id;

            this.Name = @name;

            this.Tenant_id = @tenant_id;

            this.Metadata = @metadata;

            this.Permissions = @permissions;

        }
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("tenant_id")]
        public string Tenant_id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("metadata")]
        public object Metadata { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("permissions")]
        public System.Collections.Generic.ICollection<string> Permissions { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record SyncedUser
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public SyncedUser(string @email, string @id, object @metadata, string @name, System.Collections.Generic.ICollection<SyncedRole> @roles)

        {

            this.Id = @id;

            this.Name = @name;

            this.Email = @email;

            this.Metadata = @metadata;

            this.Roles = @roles;

        }
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("metadata")]
        public object Metadata { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("roles")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<SyncedRole> Roles { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// the format of is_allowed_url() input
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record UrlAuthorizationQuery
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public UrlAuthorizationQuery(object @context, string @http_method, string @sdk, string @tenant, System.Uri @url, User @user)

        {

            this.User = @user;

            this.Http_method = @http_method;

            this.Url = @url;

            this.Tenant = @tenant;

            this.Context = @context;

            this.Sdk = @sdk;

        }
        [System.Text.Json.Serialization.JsonPropertyName("user")]
        [System.ComponentModel.DataAnnotations.Required]
        public User User { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("http_method")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Http_method { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(65536, MinimumLength = 1)]
        public System.Uri Url { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("tenant")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Tenant { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("context")]
        public object Context { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("sdk")]
        public string Sdk { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record User
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public User(object @attributes, string @email, string @firstName, string @key, string @lastName)

        {

            this.Key = @key;

            this.FirstName = @firstName;

            this.LastName = @lastName;

            this.Email = @email;

            this.Attributes = @attributes;

        }
        [System.Text.Json.Serialization.JsonPropertyName("key")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Key { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("firstName")]
        public string FirstName { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("lastName")]
        public string LastName { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("attributes")]
        public object Attributes { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record UserPermissionsQuery
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public UserPermissionsQuery(object @context, System.Collections.Generic.ICollection<string> @resource_types, System.Collections.Generic.ICollection<string> @resources, System.Collections.Generic.ICollection<string> @tenants, User @user)

        {

            this.User = @user;

            this.Tenants = @tenants;

            this.Resources = @resources;

            this.Resource_types = @resource_types;

            this.Context = @context;

        }
        [System.Text.Json.Serialization.JsonPropertyName("user")]
        [System.ComponentModel.DataAnnotations.Required]
        public User User { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("tenants")]
        public System.Collections.Generic.ICollection<string> Tenants { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("resources")]
        public System.Collections.Generic.ICollection<string> Resources { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("resource_types")]
        public System.Collections.Generic.ICollection<string> Resource_types { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("context")]
        public object Context { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record UserTenantsQuery
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public UserTenantsQuery(object @context, User @user)

        {

            this.User = @user;

            this.Context = @context;

        }
        [System.Text.Json.Serialization.JsonPropertyName("user")]
        [System.ComponentModel.DataAnnotations.Required]
        public User User { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("context")]
        public object Context { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record ValidationError
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ValidationError(System.Collections.Generic.ICollection<Loc> @loc, string @msg, string @type)

        {

            this.Loc = @loc;

            this.Msg = @msg;

            this.Type = @type;

        }
        [System.Text.Json.Serialization.JsonPropertyName("loc")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Loc> Loc { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("msg")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Msg { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record _AllTenantsAuthorizationResult
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public _AllTenantsAuthorizationResult(bool? @allow, object @debug, object @query, bool? @result, _TenantDetails @tenant)

        {

            this.Allow = @allow;

            this.Query = @query;

            this.Debug = @debug;

            this.Result = @result;

            this.Tenant = @tenant;

        }
        [System.Text.Json.Serialization.JsonPropertyName("allow")]
        public bool? Allow { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("query")]
        public object Query { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("debug")]
        public object Debug { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public bool? Result { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("tenant")]
        [System.ComponentModel.DataAnnotations.Required]
        public _TenantDetails Tenant { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record _ResourceDetails
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public _ResourceDetails(object @attributes, string @key, string @type)

        {

            this.Key = @key;

            this.Attributes = @attributes;

            this.Type = @type;

        }
        [System.Text.Json.Serialization.JsonPropertyName("key")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Key { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("attributes")]
        public object Attributes { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record _TenantDetails
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public _TenantDetails(object @attributes, string @key)

        {

            this.Key = @key;

            this.Attributes = @attributes;

        }
        [System.Text.Json.Serialization.JsonPropertyName("key")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Key { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("attributes")]
        public object Attributes { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record _UserPermissionsResult
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public _UserPermissionsResult(System.Collections.Generic.ICollection<string> @permissions, _ResourceDetails @resource, System.Collections.Generic.ICollection<string> @roles, _TenantDetails @tenant)

        {

            this.Tenant = @tenant;

            this.Resource = @resource;

            this.Permissions = @permissions;

            this.Roles = @roles;

        }
        [System.Text.Json.Serialization.JsonPropertyName("tenant")]
        public _TenantDetails Tenant { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("resource")]
        public _ResourceDetails Resource { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("permissions")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<string> Permissions { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("roles")]
        public System.Collections.Generic.ICollection<string> Roles { get; init; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record Query
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public Query()

        {

        }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record Loc
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public Loc()

        {

        }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PdpCallException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public PdpCallException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PdpCallException<TResult> : PdpCallException
    {
        public TResult Result { get; private set; }

        public PdpCallException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625